### ISSUE TITLE
static mul bench is  measuring in-place addition

### ISSUE THREAD

**Issue by mratsim** [AztecProtocol/aztec-2.0#35]
The static mul bench seems to be measuring in-place addition:

https://github.com/AztecProtocol/barretenberg/blob/d815655681e8e42db3e716afdb60d8afb2e8f279/barretenberg/src/aztec/ecc/curves/bn254/fr.bench.cpp#L221-L228

https://github.com/AztecProtocol/barretenberg/blob/d815655681e8e42db3e716afdb60d8afb2e8f279/barretenberg/src/aztec/ecc/curves/bn254/fr.bench.cpp#L291-L298

Is that intended? (As I suppose it's for multiplication with compile-time operand)

**Comment by zac-williamson** [comment]
Thanks for spotting this @mratsim . A fix has been pushed to master
